/*
creating the user account 
Required fields: firstname,lastname,email,userPassword
The userID is automatically generated by the database
*/

// A function that validates the username, email, and Password

export function isValidEmail(email) {
    // Regular expression pattern for valid email address
    var emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    
    // Test the email against the pattern
    return emailPattern.test(email);
  }
  

  export function isValidPassword(password){
     // Regular expression pattern for password validation
    if(password.length<8)return false;
    const passwordPattern = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{8,}$/;

  // Test the password against the pattern
     return passwordPattern.test(password);
  }


export function validateUsernameAndPassword(firstname='',lastname='',
    firstPassword='',confirmPassword=''){

        //all fields should not be empty
        //firstPassword should be same as confirm password
        //check if all fields are not empty

        const isFieldEmpty = firstname.trim()==='' || lastname.trim()==='' ||
         firstPassword.trim() === '' || confirmPassword.trim()==='';
        if(!isFieldEmpty){
            
            //this part of the code checks for the validity of the password
            //The password length should be at least 8
            //it must also include lowercase, uppercase and numbers
            //the firstPassword must equal the confirm password
            if(isValidPassword(firstPassword) && firstPassword===confirmPassword)return true;
            else return false;
        }
        return false;
        
}


